export * from './Icons'
export * from './MenuIcon';
export * from './IncreaseIcon';
export * from './EditIcon';
export * from './ReductionIcon';
export * from './DeleteIcon';
export * from './PlusIcon';
export * from './StatisticIcon';
export * from './ArrowIcon';
export * from './CloseIcon';
export * from './SettingsIcon'